feat: scala 3 derivation
indoorvivants/toml-scala pull request #8
Opened 2024-12-14 14:52 UTC by i10416

close https://github.com/indoorvivants/toml-scala/issues/5
This PR adds Scala 3 derivation.

It pass all the test except one which uses `Map`, that does not seem to have `K0.ProductInstances`.

See core/src/test/scala-3/toml/CodecSpec.scala.

2024-12-14 14:57 UTC, i10416 commented on core/src/test/scala-3/toml/CodecSpec.scala
> +  // test("Table (5)") {
Some tests are skipped because they result in compile error(or crash?).

2024-12-14 16:13 UTC, i10416 commented on core/src/main/scala/toml/Codec.scala
> +  private[toml] def optional: Boolean = false
This field makes it easier to handle default value for missing field. toml does not have the concept of `null` or `nil`.

2024-12-14 16:14 UTC, i10416 commented on core/src/test/scala-3/toml/CodecSpec.scala
> +trait CodecSpecExtras {self: CodecSpec =>
Scala 3 derivation cannot pass these tests(yet)

2024-12-14 17:03 UTC, i10416 commented on core/src/main/scala-3/toml/derivation/DerivedProductCodec.scala
> +                      .map(_.asInstanceOf[t])
defaultParams is `Map[Strng, Any]`, so you need `asInstanceOf`

2024-12-14 17:06 UTC, i10416 commented on core/src/main/scala-3/toml/derivation/DerivedProductCodec.scala
> +                        case None if codec.optional => Right(None.asInstanceOf[t])
optional  returns `true` if and only if codec is of type `Codec[Option[?]]`, so it is safe to use `None.asInstanceOf[t]` where `t` is of type `Option[?]`.

2024-12-14 18:11 UTC, i10416 commented on core/src/test/scala-3/toml/CodecSpec.scala
> +trait CodecSpecExtras {self: CodecSpec =>
Anyway, you can now enjoy most of the niceties of codec derivation.

2024-12-16 04:50 UTC, i10416 commented on core/src/main/scala-3/toml/derivation/DerivedProductCodec.scala
> +              map.keySet.diff(labelling.elemLabels.toSet).headOption match
Scala 2 derivation does not allow redundant fields for type.

2024-12-16 04:51 UTC, i10416 commented on core/src/main/scala-3/toml/derivation/DerivedProductCodec.scala
> +      inst.unfold[Acc]((value, (labelling.elemLabels, index), (Nil, "")))(
It uses `unfold` instead of `constructA` because Scala 2 derivation performs stateful operation on labels and index.

2024-12-16 04:53 UTC, i10416 commented on core/src/main/scala-3/toml/derivation/DerivedProductCodec.scala
> +                    ((value,(tail, index),(path,e)), Some(None.asInstanceOf[t]))
We can use `None` as default value for field of type `Option[t]`.

2024-12-17 05:23 UTC, i10416 commented
@keynmol Hello, I guess you're the maintainer of this project. Would you mind if I ask to review this PR?

2024-12-26 13:02 UTC, keynmol commented
Hi @i10416!

Sorry for slow response on this, blame holiday season.

I will look at this PR in the next couple of weeks, thanks for taking a stab at this!

I have my own version somewhere as well, so I'll compare issues and see how they can be merged to achieve perfection.

2024-12-26 17:49 UTC, i10416 commented
I see. Have a nice holiday season!

2025-01-11 10:08 UTC, keynmol requested changes
In general, this works, good job!

I added a few comments: 

1. one method needs to be extensively refactored, very difficult to follow
2. as many things as possible should be made `private[toml]` (macros often prevent hiding _some_ details, but hopefully various traits can be hidden here)
3. the project doesn't yet have a `.scalafmt.conf`, to avoid reformatting everything at once (I will do it after your PR), would you mind formatting just the larger files you added in the PR using this config?

```conf
version = "3.8.3"
runner.dialect = scala213source3

fileOverride {
  "glob:**.sbt" {
    runner.dialect = scala212source3
  }

  "glob:**/project/**.*" {
    runner.dialect = scala212source3
  }

  "glob:**/scala-3/**/*.scala" {
    runner.dialect = scala3
    rewrite.scala3.insertEndMarkerMinLines = 10
    rewrite.scala3.removeOptionalBraces = true
    rewrite.scala3.convertToNewSyntax = true
  }
}
``` 

This will be the config that I will use for the rest of the project

2025-01-11 10:08 UTC, keynmol commented on core/src/main/scala-3/toml/derivation/DerivedProductCodec.scala
> +      type Acc = (Value, (/*labels: */Seq[String], Index), Parse.Error)
I think using a tuple here makes things more confusing than they have to be – instead, let's use a case class with meaningful field names and refer to them directly, instead of destructuring with `@unchecked`.

At the moment the logic is very different to review because of the amount of tuples

2025-01-11 10:08 UTC, keynmol commented on core/src/main/scala-3/toml/derivation/syntax.scala
> +trait DerivedSyntax {self: Codec.type =>
this can be made `private[toml]`

2025-01-11 10:08 UTC, keynmol commented on core/src/main/scala-3/toml/derivation/ProductDefaultsMacro.scala
> +    def defaultParmasImpl[T](using quotes: Quotes, tpe: Type[T]): Expr[Map[String, Any]] =
typo - Parmas instead of Params

seems like the typo is copied from https://github.com/lampepfl/dotty-macro-examples/blob/main/defaultParamsInference/src/macro.scala

2025-01-11 10:08 UTC, keynmol commented on core/src/main/scala-2/toml/derivation/syntax.scala
> +trait DerivedSyntax {self: Codec.type => }
can be made `private[toml]`

2025-01-11 10:08 UTC, keynmol commented on core/src/main/scala-2/toml/TomlVersionSpecific.scala
> +trait TomlVersionSpecific { self: Toml.type =>
may be this can be made `private[toml]`?

2025-01-18 09:55 UTC, i10416 commented on core/src/main/scala-3/toml/derivation/DerivedProductCodec.scala
> +      type Acc = (Value, (/*labels: */Seq[String], Index), Parse.Error)
Thanks for suggestion! I'll fix it.

2025-01-18 09:56 UTC, i10416 commented on core/src/main/scala-3/toml/derivation/syntax.scala
> +trait DerivedSyntax {self: Codec.type =>
Yes. I agree.

2025-01-18 09:56 UTC, i10416 commented on core/src/main/scala-3/toml/derivation/ProductDefaultsMacro.scala
> +    def defaultParmasImpl[T](using quotes: Quotes, tpe: Type[T]): Expr[Map[String, Any]] =
Yes, I borrowed implementation from there.

2025-01-18 09:57 UTC, i10416 commented
> one method needs to be extensively refactored, very difficult to follow

I see,I will make diffs smaller.

2025-01-19 17:20 UTC, i10416 commented on core/src/main/scala-3/toml/derivation/DerivedProductCodec.scala
> +      type Acc = (Value, (/*labels: */Seq[String], Index), Parse.Error)
Done at https://github.com/indoorvivants/toml-scala/pull/8/commits/ba3124e419f62e3c7ea470474f25529940e534e9

2025-01-19 17:20 UTC, i10416 commented on core/src/main/scala-3/toml/derivation/ProductDefaultsMacro.scala
> +    def defaultParmasImpl[T](using quotes: Quotes, tpe: Type[T]): Expr[Map[String, Any]] =
https://github.com/indoorvivants/toml-scala/pull/8/commits/68e9f0bf0ade1af80b8203bf1d4c52cf9b3077e3

2025-02-08 11:43 UTC, i10416 commented
@keynmol Hi, I addressed the code reviews.
 
Could you check the changes?

2025-02-09 14:00 UTC, keynmol commented
Thanks @i10416! The context changes look much cleaner 👍 

I have some minor things I'd like to change before this gets released (and get more familiar with the shapeless3), but I think this is good to merge!

2025-02-09 14:00 UTC, merged